[project]
name = "app"
version = "0.1.3"
description = "a proxy checker app"
requires-python = ">=3.12"
dependencies = [
    "mm-base1==0.1.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest~=8.3.3",
    "pytest-xdist~=3.6.1",
    "pytest-httpserver~=1.1.0",
    "coverage~=7.6.0",
    "ruff~=0.7.4",
    "pip-audit~=2.7.3",
    "bandit~=1.7.10",
    "mypy~=1.13.0",
    "types-PyYAML~=6.0.12.20240917",
]

[tool.mypy]
python_version = "3.12"
implicit_reexport = true
warn_no_return = false
strict = true
plugins = "pydantic.mypy"
[[tool.mypy.overrides]]
module = ["wtforms.*", "telebot.types.*", "telebot.util.*"]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["app.routers.*"]
disable_error_code = ["no-untyped-def"]

[tool.ruff]
line-length = 130
target-version = "py312"
lint.select = [
    "F", # Pyflakes
    "E", "W", # pycodestyle
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "COM", # flake8-commas
    "C40", # flake8-comprehensions
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "T20", # flake8-print
    "RUF", # Ruff-specific rules
]
lint.ignore = [
    "A003", # builtin-attribute-shadowing
    "B008", # function-call-argument-default
    "RUF012",
    "COM812",
]
[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B311"]
